version: "3.4"

services:
  push-nuget:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: push-nuget
  build:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
