name: 'Push NuGet'
on:
  release:
    types: [published]
jobs:
  push-nuget:
    name: Push nuget package
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker-compose build --build-arg version="$GITHUB_REF_NAME" push-nuget
      - name: Run tests
        run: docker-compose run --rm push-nuget --api-key $NUGET_API_KEY
