name: 'Test'

on: push

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker-compose run test
